name: "Uppercase"

inputs:
  text:
    description: "text to be convert to Uppercase"
    required: true

outputs:
  uppercase-text:
    description: "text to be convert to Uppercase"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.txt }}
