name: Continuous Integration
on: push

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Chekout # ワークフローをトリガーしたリポジトリとブランチのみをクローンする
        uses: actions/checkout@v2.0.0 
      
      - name: set node.js 12.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-${{ matrix.os }}-${{ matrix.node }}
          path: coverage

  check-Python-version:
    name: Version Check
    runs-on: ubuntu-latest
    steps:
      - name: Chekout # ワークフローをトリガーしたリポジトリとブランチのみをクローンする
        uses: actions/checkout@v2.0.0 
      - name: check version
        run: |
          import sys
          print(sys.version)
        shell: python

