name: Test
on: 
  pull_request:
  push:
    branches:
      - master
      - 'release/*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2.0.0
      - id: uppercase
        uses: ./.github/actions/
        with:
          text: hello, world!
      - name: print converted text
        run: echo "${{ steps.uppercase.outputs.uppwercase-text}}"
